### PR TITLE
Cmedb export shares

### PR DESCRIPTION
**Pull request by ILightThings**
Added the ability to exports shares from cmedb.

simple
```
cmedb (default)(smb) > export shares simple a.csv

id,computerid,userid,name,remark,read,write
1,3,2,ADMIN$,Remote Admin,1,1
2,3,2,C$,Default share,1,1
3,3,2,DemoSystem,,1,1
4,3,2,Materclass,,1,1
5,3,2,NETLOGON,Logon server share ,1,1
6,3,2,SYSVOL,Logon server share ,1,0
```

detailed
```
cmedb (default)(smb) > export shares detailed b.csv

id,computerid,userid,name,remark,read,write
1,DC01,LIGHT\administrator,ADMIN$,Remote Admin,True,True
2,DC01,LIGHT\administrator,C$,Default share,True,True
3,DC01,LIGHT\administrator,DemoSystem,,True,True
4,DC01,LIGHT\administrator,Materclass,,True,True
5,DC01,LIGHT\administrator,NETLOGON,Logon server share ,True,True
6,DC01,LIGHT\administrator,SYSVOL,Logon server share ,True,False
```

### CODE REVIEW

**Comment by maaaaz** [comment]
Thanks but please use the builtin `csv` Python module to ensure proper charset support.
And please quote all to avoid any issue, and specify the lineterminator, for instance: 
`csv.writer(export_file, delimiter=";", quoting=csv.QUOTE_ALL, lineterminator='\n')`

**Comment by maaaaz** [comment]
Your `get_user()` and `get_host` functions can be simplified and more robust by calling `self.db.get_users/computers(arg)` functions and passing args, instead of looping.

cf. https://github.com/Porchetta-Industries/CrackMapExec/issues/604

**Comment by ILightThings** [comment]
Thank you! I did not know about this functionally. I will fix this within a few days.

**Comment by ILightThings** [comment]
Sorry for the delay. The function has been fixed using @maaaaz suggestions.

**Comment by mpgn** [comment]
All good for you @maaaaz ?

**Comment by maaaaz** [comment]
Yes sure, thank you all.
The next step would be to rewrite all other CSV export functions (host, creds, detailed) to follow the same CSV output format

**Comment by ILightThings** [comment]
If you want, I can't take the reigns one that. 

You've been a huge help showing me the inner API and I time coming up I can dedicate.

**Comment by mpgn** [comment]
I will probably merge this one this week ! Do you have a twitter @maaaaz ?

**Comment by maaaaz** [comment]
@mpgn nope

**Pull request merged**
