### PR TITLE
Bump aardwolf to version 0.2.0

### PR DESCRIPTION
**Pull request by mpgn**
Bump aardwolf to version 0.2.0

### CODE REVIEW

**Comment by mpgn** [comment]
Still work in progress 

image

**Comment by mpgn** [comment]
image

**Comment by mpgn** [comment]
@lap1nou do you have a twitter ? or an email adress to get your adress so I can send you a cme coin :)

**Comment by lap1nou** [comment]
Hey sure thank you, here is my twitter: @lapinousexy

**Pull request merged**
