### PR TITLE
Add GMSA module

### PR DESCRIPTION
**Pull request by swisskyrepo**
A simple module to request GMSA passwords from LDAP :smirk:

### CODE REVIEW

**Review by its0x08 — APPROVED** [review]

**Comment by mpgn** [comment]
I will better as a core option on LDAP protocol like this:

> cme ldap <ip> -u computer$ -p password --gmsa

**Comment by swisskyrepo** [comment]
Do you need me to do anything ? :)

**Comment by mpgn** [comment]
Hello, you can add the code directly on the `cme/protocols/ldap.py` instead of the module. You can add the class MSDS_MANAGEDPASSWORD_BLOB into `cme/protocols/ldap`

I can do it but if you do it you will get the coin héhé :)

**Comment by mpgn** [comment]
thanks ! time to review :)

**Comment by mpgn** [comment]
Can't make it work on my side

image

**Comment by mpgn** [comment]
I need to setup ldaps in my lab :fuck:

**Comment by mpgn** [comment]
I rewrite everything, can you check if this is working on your side ?

**Comment by swisskyrepo** [comment]
Looks good on my side 👍 
image

**Pull request merged**
