### PR TITLE
New module wcc

### PR DESCRIPTION
**Pull request by fpreynaud**
This module checks various configuration items on Windows machines, such as LSA cache, hash storage format, etc.

Example output:
image

### CODE REVIEW

**Comment by Dfte** [comment]
Let's goooooooo!

**Comment by NeffIsBack** [comment]
@fpreynaud Save a Local copy of your repo, than do:
```git reset --hard ad152dd9d502055c010fbbf81c98f8e7cd2ed811
git push --force
```

**Comment by fpreynaud** [comment]
The PR was closed by deleting the fork, reforking and doing what you suggest does not work, unfortunately.
Really sorry about that, that's really a big fail from me.

**Comment by NeffIsBack** [comment]
Git clone the repo and just do the stuff inside the new one, that should work

**Comment by NeffIsBack** [comment]
Is it possible to get the fork back maybe?:

https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository

**Comment by fpreynaud** [comment]
Not without contacting support, apparently:

image

**Comment by NeffIsBack** [comment]
Please contact them so you can get back the repo and force push to delete the changes

**Comment by fpreynaud** [comment]
It's done. I hope they'll respond quickly

**Comment by fpreynaud** [comment]
Just did it. Looks all good now.
Sorry again for the mess !

**Comment by NeffIsBack** [comment]
Atleast the code is gone now😅
But why closing the PR? Still looks like a nice module

**Comment by Dfte** [comment]
We need to check a few things before. Will open a new one june 15

**Comment by NeffIsBack** [comment]
The private version is released now in the new repository at https://github.com/mpgn/CrackMapExec

This PR looked really cool. Can you open up a new PR on the new repository?

**Comment by fpreynaud** [comment]
Yep, it's coming very soon :)

**Comment by NeffIsBack** [comment]
Awesome🔥

**Pull request closed without merging**
