### PR TITLE
Add the MSOL module to dump msol cleartext password

### PR DESCRIPTION
**Pull request by DaahtKing**
## Module description :

This module will dump the cleartext password for the user **MSOL_xxx** on the Azure AD Connect server _(AD Connect server name is in LDAP description of MSOL_xxx account)_. 
The **Msol_xxx** user is in charge of hash synchronization from local Active Directory to Azure AD, so he has DCSync rights on the active directory.

## Module Usage :

`crackmapexec smb -u user -p password -M msol `

### CODE REVIEW

**Comment by mpgn** [comment]
Hello, thanks for the module,

This path `$db=@(C:\"Program Files"\"Microsoft SQL Server"\150\Tools\Binn\SqlLocalDB.exe info | findstr /i ADSy)` is harcoded but what if folder 150 doesn't exist ? like the exemple on https://blog.xpnsec.com/azuread-connect-for-redteam/ his path is 110 not 115 .

**Comment by DaahtKing** [comment]
> Hello, thanks for the module,
> 
> This path `$db=@(C:\"Program Files"\"Microsoft SQL Server"\150\Tools\Binn\SqlLocalDB.exe info | findstr /i ADSy)` is harcoded but what if folder 150 doesn't exist ? like the exemple on https://blog.xpnsec.com/azuread-connect-for-redteam/ his path is 110 not 115 .

Hey, thanks for your answer

So normally when installing Azure AD Connect, the SqlLocalDB binary is installed in the 150 folder by default. Microsoft only refers to it in this example https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/resolve-model-database-corruption-sqllocaldb. In doubt, I modified the script which is run to dynamically resolve the binary name. Here is an example after modification: 
image

**Comment by mpgn** [comment]
Merci, 

Par rapport au powershell direct en base64, c'est pas très pratique si on veut modifier rapidement le ps1. Est-ce que tu le placer directement ici dans un dossier "msol_dump" par exemple https://github.com/Porchetta-Industries/CrackMapExec/tree/master/cme/data

Et ensuite le load et encoded en base64 directement dans le module.

Tu peux t'inspirer de: 
- https://github.com/Porchetta-Industries/CrackMapExec/pull/710/files
- https://github.com/Porchetta-Industries/CrackMapExec/pull/637/files

**Comment by KenjiEndo15** [comment]
Hey, great PR :+1: 

By the way, maybe you could also add a way to find the server where Azure AD Connect is installed?

The researcher (Aymeric Palhière) from Synacktiv showed a query in his [blog post](https://www.synacktiv.com/en/publications/azure-ad-introduction-for-red-teamers.html)  :
```
ldapsearch -H ldap://DC01.GOTHAM.LAB:389 -D "GOTHAM\joker" -w "****" -b "DC=GOTHAM,DC=LAB" '(description=*Azure*)' description
```
From the result, you can fetch the server (in description).

Also, maybe displaying the path where the `msol.ps1` script is dropped, as it would help if we have to remove it manually (a bug could happen before it even gets deleted automatically).

Thank you for your work!

**Comment by mpgn** [comment]
Thanks for the PR, the pr is now merged on the last official repository of CrackMapExec

https://github.com/mpgn/CrackMapExec/commit/324996c2e1399c7d7fad13da1c231763eced4504
https://github.com/mpgn/CrackMapExec/commit/1fb31248a934c8139c3bcfdfd03571f51d531e7a
https://github.com/mpgn/CrackMapExec/commit/02fd427e34e81e014f6996876ca7f7c52a9e607f
https://github.com/mpgn/CrackMapExec/commit/a2a844c3cbb4331e618439b599f80d23e892e8eb
https://github.com/mpgn/CrackMapExec/commit/34b88f80af795d6d3f262213497d5e5d19e84866

Send me a DM on twitter to get your coin :)

**Pull request closed without merging**
