### PR TITLE
Fix kerberos authentication

### PR DESCRIPTION
**Pull request by zblurx**
Hey,

This PR fix kerberos authentication, previously working only with tickets in KRB5CNAME.
Now, -k is use to specify that the authentication flow should use kerberos, so it is working with cleartext, nthash and obviously aesKey
A new option --use-kcache is used to specify that the authentication should use KRB5CNAME.

Very useful when working on domain with Protected Users :)

### CODE REVIEW

**Comment by mpgn** [comment]
Hello, this is awesome I like it 🥇 

Can you review the change I made ? :)

**Review by zblurx — COMMENTED** [review]
Thank you and well done on the fixes, now it looks perfect.

**Comment by mpgn** [comment]
did you test with mssql @zblurx ? I notice there is a kerberoslogin for mssql also !

**Comment by zblurx** [comment]
I did not know. Gonna test this :)

**Comment by mpgn** [comment]
done @zblurx

**Comment by mpgn** [comment]
image

**Pull request merged**
